"""Designated deterministic Year-2 release generator. Python 3.11+ and PyYAML.

Only the six declared release envelopes are written. Authored inputs are read-only.
--check compares generated bytes; --package creates a deterministic analysis ZIP.
A different existing package is never overwritten. No primary sources are read.
"""
from __future__ import annotations
import argparse,collections,hashlib,json,os,re,subprocess,unicodedata,urllib.parse,zipfile
from pathlib import Path
import yaml

HERE=Path(__file__).resolve().parent
YEAR=HERE.parent
ROOT=YEAR.parent
REPO=ROOT.parent.parent
ADMIN=YEAR/'00 Corpus Administration'
SPEC=HERE/'COTE_Y2_RELEASE_SPEC.json'
NAMES=['COTE_Y2_SOURCE_CHECKSUMS.sha256','COTE_Y2_CORPUS_MANIFEST.md','COTE_Y2_CORPUS_INDEX.json','COTE_Y2_DELIVERY_AUDIT.md','COTE_Y2_V2_FINAL_DELIVERY_AUDIT.json','COTE_Y2_ARTIFACT_CHECKSUMS.sha256']
OUTPUTS={n:ADMIN/n for n in NAMES}

def sha(b): return hashlib.sha256(b).hexdigest()
def js(o): return (json.dumps(o,ensure_ascii=False,indent=2)+'\n').encode('utf-8')
def rel(p): return p.relative_to(REPO).as_posix()
def url(p,base=ADMIN): return urllib.parse.quote(os.path.relpath(p,base).replace('\\','/'),safe='/')
def meta(data):
 t=data.decode('utf-8','strict')
 if t.startswith('---\n'):
  m=yaml.safe_load(t.split('---',2)[1]);assert isinstance(m,dict);return m
 return {}
def nofences(t): return re.sub(r'(?ms)^(`{3,}|~{3,}).*?^\1[^\n]*\n?','',t)
def targets(t):
 return re.findall(r'\]\(([^\n)]*)\)',t)+re.findall(r'^\[[^\]]+\]:\s*(\S+)',t,re.M)
def anchors(t):
 seen=collections.Counter();out=set(re.findall(r'<a\s+(?:name|id)=["\']([^"\']+)',t))
 for h in re.findall(r'^#{1,6}\s+(.+?)\s*#*$',nofences(t),re.M):
  h=re.sub(r'\[([^\]]+)\]\([^)]*\)',r'\1',h);h=re.sub(r'<[^>]+>','',h).lower()
  h=''.join(c for c in h if c in '-_ ' or unicodedata.category(c)[0] in 'LN').replace(' ','-')
  n=seen[h];seen[h]+=1;out.add(h+(f'-{n}' if n else ''))
 return out

def record(p,b,group):
 m=meta(b) if p.suffix=='.md' else {}
 typ=m.get('artifact_type')
 if not typ:
  typ='governing_architecture' if 'Architecture' in p.name else 'analytical_method' if 'METHOD' in p.name else 'reproducibility_tool' if p.suffix=='.py' else 'checksum_inventory' if p.suffix=='.sha256' else 'retrieval_or_release_data' if p.suffix=='.json' else 'reference_document'
 boundary=m.get('source_boundary',m.get('analysis_boundary',m.get('scope')))
 if boundary is None: boundary='Y1FF historical foundation' if '/02 Year 1 ' in str(p).replace('\\','/') else 'method/infrastructure; no independent narrative claim'
 subject=m.get('primary_home_subject',m.get('architecture_slot',m.get('title',typ)))
 return {'filename':p.name,'artifact_type':typ,'source_boundary':boundary,'status':m.get('authority_state',m.get('status','supporting_infrastructure')),'word_count':len(b.decode('utf-8').split()) if p.suffix=='.md' else None,'word_count_method':'UTF-8 whitespace-delimited tokens including metadata; not a Japanese linguistic word count' if p.suffix=='.md' else 'not applicable to structured data/tool/checksum','byte_count':len(b),'sha256':sha(b),'supersession_relation':{'supersedes':m.get('supersedes',[]),'superseded_by':m.get('superseded_by',[])},'primary_home_subject':subject,'relative_path':rel(p),'package_group':group}

def main():
 ap=argparse.ArgumentParser();ap.add_argument('--check',action='store_true');ap.add_argument('--package',type=Path);args=ap.parse_args()
 spec=json.loads(SPEC.read_text(encoding='utf-8'));core={REPO/p:(REPO/p).read_bytes() for p in spec['core_paths']}
 assert len(core)==len(spec['core_paths'])
 for p,b in core.items():
  assert p.is_relative_to(REPO) and p.suffix in {'.md','.json','.sha256','.py'},rel(p)
  b.decode('utf-8','strict')
  if p.suffix=='.json':json.loads(b)
  elif p.suffix=='.md':meta(b)
 lock=meta(core[ADMIN/'COTE_Y2_V2_ARCHIVAL_LOCK.md']);state=lock['release_state'];frozen=state=='frozen'
 source_spec=json.loads((HERE/'COTE_Y2_SOURCE_ROUTING_SPEC.json').read_text(encoding='utf-8'))
 source_sum=''.join(f"{s['source_sha256']}  {s['source_relative_path']}\n" for s in source_spec['sources']).encode()
 core[OUTPUTS[NAMES[0]]]=source_sum
 assert len(source_spec['sources'])==17
 preservation=[]
 for s in spec['preserved_source_local_artifacts']:
  b=core[REPO/s['path']];assert len(b)==s['bytes'] and sha(b)==s['sha256'],s['path'];preservation.append({'path':s['path'],'sha256':sha(b),'unchanged':True})
 evidence=json.loads(core[HERE/'COTE_Y2_EVIDENCE_INDEX.json'])
 # Source specifications retain the original ID counts, independently of report prose.
 assert sum(s['expected_evidence_count'] for s in source_spec['sources'])==2697
 jp=next(p for p in core if p.name=='COTE_Y2_13_JAPANESE_TERMINOLOGY_AND_PASSAGE_INDEX.md')
 entries=re.findall(r'^## (JP-[A-E]\d{2})\b',core[jp].decode(),re.M)
 if not entries: entries=re.findall(r'^### (JP-[A-E]\d{2})\b',core[jp].decode(),re.M)
 assert len(entries)==43 and len(set(entries))==43,len(entries)
 protocol=ROOT/'00 Frameworks and Methods/COTE_BEHAVIORAL_RECONSTRUCTION_PROTOCOL_THROUGH_Y2.md'
 assert len(re.findall(r'^## Calibration \d+ [—-] ',core[protocol].decode(),re.M))==23
 specialists=[next(p for p in core if p.name.startswith(f'COTE_Y2_{i:02d}_')) for i in range(1,14)]
 for p in specialists+[next(p for p in core if p.name=='COTE_Y2_FULL_SYNTHESIS.md')]:assert meta(core[p])['status']=='canonical',p.name
 md_files={p:b.decode() for p,b in core.items() if p.suffix=='.md'}
 forbidden=[]
 for p,t in md_files.items():
  body=nofences(t)
  if re.search(r'sandbox:/|\[TODO\]|<INSERT(?:_| )|^<<<|^BEGIN (?:ASSISTANT|RESPONSE)',body,re.M): forbidden.append(rel(p))
 assert not forbidden,forbidden
 # A repeated analytical paragraph predating this release is preserved history.
 # New long verbatim prose requires a deliberate authored disposition, not autoacceptance.
 paragraphs=collections.defaultdict(list)
 for p,t in md_files.items():
  if p.is_relative_to(YEAR) or p==protocol:
   for part in re.split(r'\n\s*\n',nofences(t)):
    part=part.strip()
    if len(part.split())>=80 and not part.startswith(('|','-','>','#','---','1.')):
     paragraphs[part].append(rel(p))
 duplicates=[]
 for paragraph,ps in paragraphs.items():
  if len(set(ps))<2:continue
  historical=True
  for path in set(ps):
   old=subprocess.run(['git','show',spec['baseline_commit']+':'+path],cwd=REPO,capture_output=True)
   if old.returncode or paragraph not in old.stdout.decode('utf-8'):historical=False
  duplicates.append({'sha256':sha(paragraph.encode()),'words':len(paragraph.split()),'paths':sorted(set(ps)),'disposition':'pre-existing canonical repetition preserved' if historical else 'UNREVIEWED_NEW_DUPLICATION'})
 assert all(d['disposition']!='UNREVIEWED_NEW_DUPLICATION' for d in duplicates),duplicates
 records=[]
 for p,b in sorted(core.items(),key=lambda x:rel(x[0])):
  group='historical_Y1_foundation' if '02 Year 1 Definitive Second Pass' in p.parts else 'governing_methods' if '00 Frameworks and Methods' in p.parts else 'license_notices' if p.parent==REPO else 'Year_2_release'
  records.append(record(p,b,group))
 envelopes=[rel(OUTPUTS[n]) for n in NAMES[1:]]
 idx={'schema':'cote-y2-corpus-index-v1','release_id':spec['release_id'],'release_state':state,'source_boundary':'Y2SL','current_entrypoint':spec['entrypoint'],'core_artifact_count':len(records),'scope_note':spec['package_scope_note'],'artifacts':records,'release_envelopes':envelopes,'envelope_hash_authority':'COTE_Y2_ARTIFACT_CHECKSUMS.sha256 covers manifest/index/audits; detached archive checksum covers that checksum file','source_local_preservation':preservation,'generated_by':rel(Path(__file__))}
 common=f'''---
series: COTE
artifact_type: {{kind}}
scope: Y2
generation: V2
status: canonical
authority_state: canonical
source_boundary: Y2SL
supersedes: []
superseded_by: []
do_not_use_as_current_authority: false
---

'''
 manifest=common.format(kind='manifest')+f'''# Year 2 V2 corpus manifest

Release `{spec['release_id']}`; state `{state}`. Start with the [README]({url(REPO/spec['entrypoint'])}). The manifest covers {len(records)} core artifacts plus the generated release envelopes listed below. All paths preserve repository-relative layout in the archive.

{spec['package_scope_note']}

All core records carry the architecture-required filename, type, source boundary, status, words, bytes, SHA-256, supersession and primary-home subject. Machine-readable values live in [COTE_Y2_CORPUS_INDEX.json](COTE_Y2_CORPUS_INDEX.json). Word counts use whitespace-delimited tokens and include metadata; structured data/tools have no linguistic word-count claim.

'''
 for o in records:
  def scalar(v):return json.dumps(v,ensure_ascii=False,default=str)
  manifest+=f"## {o['filename']}\n\n- path: [{o['relative_path']}]({url(REPO/o['relative_path'])})\n- type: `{o['artifact_type']}`; status: {scalar(o['status'])}\n- source boundary: {scalar(o['source_boundary'])}\n- primary home: {scalar(o['primary_home_subject'])}; group: `{o['package_group']}`\n- words: {o['word_count'] if o['word_count'] is not None else 'not applicable'}; bytes: {o['byte_count']}; SHA-256: `{o['sha256']}`\n- supersession: {scalar(o['supersession_relation'])}\n\n"
 manifest+='## Generated release envelopes and self-reference rule\n\n'
 for n in NAMES[1:]:manifest+=f'- [{n}]({n})\n'
 manifest+='\nThese envelopes are not recursively enumerated as their own hashed content. The artifact checksum inventory binds all package files except itself; the detached ZIP checksum binds the entire archive. The publication receipt binds the exact committed state and successful remote audit. Primary sources, source extracts, working drafts and runtime files are excluded. Regenerate with the designated project-local generator; never edit this output by hand.\n'
 generated={OUTPUTS[NAMES[0]]:source_sum,OUTPUTS[NAMES[1]]:manifest.encode(),OUTPUTS[NAMES[2]]:js(idx)}
 # Validate file links against the complete declared package, including future envelopes.
 available=set(core)|set(OUTPUTS.values());link_count=0;anchor_count=0;errors=[];anchor_cache={}
 for p,t in md_files.items():
  for raw in targets(t):
   target=raw.strip()
   if not target or target.startswith(('https://','http://','mailto:')):continue
   bits=target.split('#',1);dst=(p.parent/urllib.parse.unquote(bits[0])).resolve() if bits[0] else p
   if dst not in available:
    errors.append({'file':rel(p),'target':target,'reason':'outside package or missing'});continue
   link_count+=1
   if len(bits)>1 and bits[1] and dst in md_files:
    frag=urllib.parse.unquote(bits[1]);anchor_cache.setdefault(dst,anchors(md_files[dst]))
    if frag not in anchor_cache[dst]:errors.append({'file':rel(p),'target':target,'reason':'missing heading anchor'})
    anchor_count+=1
 assert not errors,json.dumps(errors,ensure_ascii=False)
 audit={'schema':'cote-y2-final-delivery-audit-v1','release_id':spec['release_id'],'release_state':state,'result':'PASS_LOCAL_CONTENT_AND_PACKAGE','publication_verification':'See exact-commit external release receipt; this deterministic content audit makes no unobserved CI claim','core_artifact_count':len(records),'package_file_count':len(available),'source_boundary':'Y2SL','year3_narrative_evidence_used':False,'source_local_preserved':len(preservation),'source_identity_count':17,'original_evidence_id_count':2697,'japanese_passage_entry_count':len(entries),'protocol_calibration_count':23,'specialist_index_slots':13,'full_synthesis_present':True,'utf8':'PASS','yaml_json':'PASS','internal_file_links_checked':link_count,'heading_anchors_checked':anchor_count,'link_errors':errors,'forbidden_wrappers_or_placeholders':forbidden,'new_long_verbatim_paragraph_duplicates':0,'preserved_long_repetition_dispositions':duplicates,'checksums':'Generated deterministically; verify byte-for-byte with --check and archive member readback','source_binaries_in_package':False,'source_local_preservation':preservation}
 auditmd=common.format(kind='delivery_audit')+f'''# Year 2 V2 delivery audit

**PASS — local content, preservation and package checks.** Release state: `{state}`. Remote publication verification is recorded separately for the exact branch head; this report does not claim CI success before it has been observed.

- {len(records)} core artifacts; {len(available)} total package members, including release envelopes.
- Seventeen source-local artifacts match the starting boundary byte-for-byte.
- Seventeen source identities; 2,697 preserved evidence IDs; 43 Japanese retrieval entries; 23 calibrated protocol cases.
- Thirteen specialist/index slots and the full synthesis are canonical through Y2SL.
- UTF-8, YAML/JSON, declared package membership, {link_count} internal file links and {anchor_count} heading anchors pass.
- No new long verbatim analytical-paragraph duplication, forbidden placeholder or chat wrapper was found. {len(duplicates)} pre-existing long-repetition groups are preserved and individually identified in the machine audit.
- No primary-source binaries, Year-3 narrative analysis, extracted artwork, raw chapter exports or private work files are included.

## What the checks establish

The source checksum inventory records the identities independently verified from the external EPUBs during closeout. The evidence-router generator checks paragraph/resource bounds, source hashes and canonical locator conventions when supplied those sources; the release generator operates on analytical artifacts only. Structural locator validation does not claim that every interpretive assertion has been independently reread anew. The Japanese index's 52 short excerpts were directly verified against the locked primary sources, retaining speaker/narrator ownership and local ambiguity.

The protocol audit preserves support, determinacy, reconstruction permission and voice permission as distinct gates. All inherited question states remain intact, and the twelve new Y2H tests remain unanswered. The current correction routes cover the younger-cohort points table, V01 pictured companion and transfer destination. Earlier source-local readings and the Year-1 foundation retain their historical authority.

## Reproduction and final publication

Run [generate_y2_release.py]({url(HERE/'generate_y2_release.py')}) with `--check` to compare all six generated outputs exactly. Its `--package PATH` option writes a deterministic ZIP and detached SHA-256, then verifies each member. The artifact checksum file covers every member except itself; the detached hash closes that remaining dependency.

The exact remote commit, changed-blob readback, current-main ancestry, completed housekeeping and successful Repository integration audit must all be verified before final release eligibility. The stable branch remains separate from main unless integration is separately authorized. See the [archival-lock record](COTE_Y2_V2_ARCHIVAL_LOCK.md), [machine audit](COTE_Y2_V2_FINAL_DELIVERY_AUDIT.json), [manifest](COTE_Y2_CORPUS_MANIFEST.md) and [README]({url(REPO/spec['entrypoint'])}).
'''
 generated[OUTPUTS[NAMES[3]]]=auditmd.encode();generated[OUTPUTS[NAMES[4]]]=js(audit)
 allfiles=core|generated
 checksums=''.join(f'{sha(b)}  {rel(p)}\n' for p,b in sorted(allfiles.items(),key=lambda x:rel(x[0])))
 generated[OUTPUTS[NAMES[5]]]=checksums.encode();allfiles|=generated
 assert len(allfiles)==len(available)
 if args.check:
  bad=[rel(p) for p,b in generated.items() if not p.exists() or p.read_bytes()!=b]
  assert not bad,{'generated_outputs_differ':bad}
 else:
  for p,b in generated.items():p.write_bytes(b)
 if args.package:
  dest=args.package.resolve();dest.parent.mkdir(parents=True,exist_ok=True)
  # An in-memory archive prevents replacing an existing immutable release accidentally.
  import io
  buf=io.BytesIO()
  with zipfile.ZipFile(buf,'w',compression=zipfile.ZIP_DEFLATED,compresslevel=9) as z:
   for p,b in sorted(allfiles.items(),key=lambda x:rel(x[0])):
    info=zipfile.ZipInfo(rel(p),(2026,9,9,0,0,0));info.compress_type=zipfile.ZIP_DEFLATED;info.external_attr=0o100644<<16;info.create_system=3;z.writestr(info,b,compress_type=zipfile.ZIP_DEFLATED,compresslevel=9)
  blob=buf.getvalue()
  if dest.exists():assert dest.read_bytes()==blob,'Existing archive differs; choose a new revision filename'
  else:dest.write_bytes(blob)
  with zipfile.ZipFile(io.BytesIO(blob)) as z:
   assert z.testzip() is None and set(z.namelist())=={rel(p) for p in allfiles}
   for p,b in allfiles.items():assert z.read(rel(p))==b
  detached=dest.with_name(dest.name+'.sha256');db=f'{sha(blob)}  {dest.name}\n'.encode()
  if detached.exists():assert detached.read_bytes()==db
  else:detached.write_bytes(db)
  print(json.dumps({'archive':str(dest),'bytes':len(blob),'sha256':sha(blob),'members':len(allfiles)}))
 print(json.dumps({'result':'PASS','mode':'check' if args.check else 'generate','core_artifacts':len(records),'package_members':len(allfiles),'links':link_count,'anchors':anchor_count,'release_state':state}))

if __name__=='__main__':main()
