#!/usr/bin/env python3
"""Generate the Character Index v2 discovery surface deterministically."""

from __future__ import annotations

import argparse
from pathlib import Path
from typing import Any, Mapping, Sequence
from urllib.parse import quote

from character_index_core import (
    AuthorityGraph,
    DomainError,
    GitSnapshot,
    alias_sort_key,
    atomic_write_text,
    decode_json,
    decode_jsonl_with_lines,
    render_schema_diagnostics,
    schema_diagnostics,
    sort_key,
    validate_discovery_records,
    validate_schema_document,
)


DIMENSION_ORDER = (
    "BEHAVIOR",
    "PSYCHOLOGY",
    "SPEECH",
    "ETHICS",
    "RELATIONSHIPS",
    "IDEOLOGY",
    "DECISION_MAKING",
)

HEADER = """# Character Analysis Index

> Generated under `CHARACTER_INDEX_V2_C14N_1`; do not edit this file by hand.

This public repository is an owner-maintained, nonauthoritative migration candidate. Google Drive remains the analytical authority until the governed G8 cutover.

This discovery surface answers: “Where is substantial, reviewed analysis of this precisely scoped character subject?” It is not a migration ledger and does not claim reconstruction readiness. Mention counts, cast lists, transcripts, source text, and incidental references do not qualify by themselves.

## Reviewed entries

"""


def _alias_text(alias: Mapping[str, Any]) -> str:
    qualifiers = [alias["language"], alias["kind"]]
    if alias.get("ambiguous"):
        qualifiers.append("ambiguous")
    rendered = f"{alias['value']} ({', '.join(qualifiers)})"
    if alias.get("note") is not None:
        rendered += f" — {alias['note']}"
    return rendered


def _coverage_label(coverage: Mapping[str, Any]) -> str:
    prefix = f"{coverage['medium']} {coverage['unit']}"
    if coverage["scope_type"] == "RANGE":
        return f"{prefix} {coverage['start']}–{coverage['through']} (inclusive)"
    if coverage["scope_type"] == "DISCRETE":
        return f"{prefix} " + ", ".join(coverage["locators"])
    return f"{prefix}: {coverage['scope_note']}"


def _markdown_target(path: str, anchor: str | None) -> str:
    encoded_path = "/".join(quote(segment, safe="-._~") for segment in path.split("/"))
    if anchor is None:
        return encoded_path
    return encoded_path + "#" + quote(anchor, safe="-._~:")


def _markdown_link_label(value: str) -> str:
    return value.replace("\\", "\\\\").replace("[", "\\[").replace("]", "\\]")


def _leaf_subjects(
    record: Mapping[str, Any], by_subject: Mapping[str, Mapping[str, Any]]
) -> list[Mapping[str, Any]]:
    leaves: dict[str, Mapping[str, Any]] = {}

    def expand(subject_id: str) -> None:
        child = by_subject[subject_id]
        if child["subject_kind"] == "COMPOSITE_MODEL":
            for component in child["component_subject_ids"]:
                expand(component)
        else:
            leaves[subject_id] = child

    for component in record.get("component_subject_ids", []):
        expand(component)
    return [leaves[key] for key in sorted(leaves)]


def render(records: Sequence[Mapping[str, Any]], authority: AuthorityGraph) -> str:
    included = [
        record for record in records if record.get("curation_status") == "INCLUDED"
    ]
    if not included:
        return HEADER + "_No reviewed entries are present in the Git candidate._\n"

    by_subject = {record["analysis_subject_id"]: record for record in records}
    lines = [HEADER.rstrip(), ""]
    grouped: dict[str, list[Mapping[str, Any]]] = {}
    for record in included:
        grouped.setdefault(record["character_entity_id"], []).append(record)
    def record_order(record: Mapping[str, Any]) -> tuple[Any, ...]:
        return (
            sort_key(record["preferred_name"]),
            sort_key(record["subject_label"]),
            record["analysis_subject_id"].encode("ascii"),
        )

    for entity_id in grouped:
        grouped[entity_id] = sorted(grouped[entity_id], key=record_order)
    entity_ids = sorted(
        grouped,
        key=lambda entity_id: (
            *record_order(grouped[entity_id][0]),
            entity_id.encode("ascii"),
        ),
    )
    for entity_id in entity_ids:
        subjects = grouped[entity_id]
        entity = subjects[0]
        lines.extend(
            [
                f"### {entity['preferred_name']}",
                "",
                f"- Entity ID: `{entity['character_entity_id']}`",
                "- Entity aliases:",
            ]
        )
        entity_aliases = sorted(entity["entity_aliases"], key=alias_sort_key)
        if entity_aliases:
            for alias in entity_aliases:
                lines.append(f"  - {_alias_text(alias)}")
        else:
            lines.append("  - _None._")
        lines.append("")
        for record in subjects:
            lines.extend(
                [
                    f"#### Subject: {record['subject_label']}",
                    "",
                    f"- Analysis subject ID: `{record['analysis_subject_id']}`",
                    f"- Series: `{record['series_id']}`",
                ]
            )
            if record["subject_kind"] == "COMPOSITE_MODEL":
                leaves = _leaf_subjects(record, by_subject)
                continuities = sorted({leaf["continuity_id"] for leaf in leaves})
                lines.append("- Continuity: **Composite analytical model (not a continuity)**")
                lines.append(
                    "- Effective continuity scope (derived): "
                    + ", ".join(f"`{item}`" for item in continuities)
                )
                lines.append(
                    "- Components: "
                    + ", ".join(
                        f"`{item}`" for item in sorted(record["component_subject_ids"])
                    )
                )
            else:
                lines.append(f"- Continuity: `{record['continuity_id']}`")
            if record.get("incarnation_id") is not None:
                lines.append(f"- Incarnation: `{record['incarnation_id']}`")
            if record.get("state_id") is not None:
                lines.append(f"- State: `{record['state_id']}`")
            lines.append(f"- Inclusion basis: `{record['inclusion_basis']}`")
            dimensions = [
                item for item in DIMENSION_ORDER if item in record["analytical_dimensions"]
            ]
            if set(record["analytical_dimensions"]) != set(dimensions):
                raise DomainError(
                    f"{record['analysis_subject_id']}: generator received an unknown analytical dimension"
                )
            lines.append(
                "- Analytical dimensions: "
                + ", ".join(f"`{item}`" for item in dimensions)
            )
            subject_aliases = sorted(record["subject_aliases"], key=alias_sort_key)
            lines.append("- Subject aliases:")
            if subject_aliases:
                for alias in subject_aliases:
                    lines.append(f"  - {_alias_text(alias)}")
            else:
                lines.append("  - _None._")
            lines.append("- Analytical coverage:")
            for coverage in sorted(
                record["analytical_coverage"], key=lambda item: item["coverage_id"]
            ):
                component = (
                    f"; component `{coverage['component_subject_id']}`"
                    if "component_subject_id" in coverage
                    else ""
                )
                lines.append(
                    f"  - `{coverage['coverage_id']}`: {_coverage_label(coverage)}"
                    f"; continuity `{coverage['continuity_id']}`{component}"
                )
            lines.append("- Reviewed current evidence:")
            for evidence in sorted(record["evidence"], key=lambda item: item["evidence_id"]):
                classification = authority.classification(evidence["repository_path"])
                if evidence["review_state"] != "REVIEWED" or not authority.current_eligible(
                    evidence["repository_path"]
                ):
                    raise DomainError(
                        f"included evidence is not reviewed/current: "
                        f"{record['analysis_subject_id']}#{evidence['evidence_id']} "
                        f"({classification})"
                    )
                target = _markdown_target(
                    evidence["repository_path"], evidence.get("anchor")
                )
                marker = (
                    " — **active provisional authority**"
                    if classification == "ACTIVE_PROVISIONAL_CURRENT"
                    else ""
                )
                lines.append(
                    f"  - [`{evidence['evidence_id']}` — "
                    f"{_markdown_link_label(evidence['label'])}]({target})"
                    f"{marker}"
                )
            lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def _snapshot(root: Path, mode: str, commit: str | None) -> GitSnapshot:
    if mode == "commit":
        if commit is None:
            raise DomainError("--commit is required with --snapshot commit")
        return GitSnapshot.from_commit(root, commit)
    if commit is not None:
        raise DomainError("--commit is valid only with --snapshot commit")
    if mode == "index":
        return GitSnapshot.from_index(root)
    return GitSnapshot.from_worktree(root)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    parser.add_argument("--repo", type=Path)
    parser.add_argument("--snapshot", choices=["worktree", "index", "commit"], default="worktree")
    parser.add_argument("--commit")
    args = parser.parse_args()
    root = args.repo.resolve() if args.repo else Path(__file__).resolve().parents[1]
    snapshot = _snapshot(root, args.snapshot, args.commit)
    required_paths = {
        "registry": "characters/registry.jsonl",
        "schema": "governance/schemas/character-analysis-index.schema.json",
        "series": "series/registry.json",
        "output": "CHARACTER_ANALYSIS_INDEX.md",
    }
    required_entries = {name: snapshot.get(path) for name, path in required_paths.items()}
    missing = [
        path
        for name, path in required_paths.items()
        if required_entries[name] is None or required_entries[name].mode != "100644"
    ]
    if missing:
        raise DomainError(f"snapshot lacks required regular paths: {missing}")
    records_with_lines = decode_jsonl_with_lines(
        required_entries["registry"].data,  # type: ignore[union-attr]
        f"{snapshot.identity}:characters/registry.jsonl",
    )
    records = [record for _line_number, record in records_with_lines]
    if args.snapshot == "worktree" and records:
        raise DomainError(
            "worktree bytes cannot establish materialization; use an exact Git index or commit snapshot"
        )
    schema = decode_json(
        required_entries["schema"].data,  # type: ignore[union-attr]
        f"{snapshot.identity}:character-analysis-index.schema.json",
    )
    if not isinstance(schema, dict):
        raise DomainError("character discovery schema is not a JSON object")
    validate_schema_document(schema, "character discovery schema")
    diagnostics = []
    for line_number, record in records_with_lines:
        diagnostics.extend(
            schema_diagnostics(
                record,
                schema,
                "characters/registry.jsonl",
                line_number=line_number,
            )
        )
    failures = render_schema_diagnostics(diagnostics)
    if failures:
        raise DomainError("\n".join(failures))
    authority = AuthorityGraph(snapshot)
    series_registry = decode_json(
        required_entries["series"].data,  # type: ignore[union-attr]
        f"{snapshot.identity}:series/registry.json",
    )
    if not isinstance(series_registry, dict):
        raise DomainError("series registry is not a JSON object")
    failures = authority.errors + validate_discovery_records(
        records, series_registry, snapshot=snapshot, authority=authority
    )
    if failures:
        raise DomainError("\n".join(sorted(set(failures))))
    rendered = render(records, authority)
    output = root / "CHARACTER_ANALYSIS_INDEX.md"
    if args.check:
        current = required_entries["output"].data  # type: ignore[union-attr]
        if current != rendered.encode("utf-8"):
            raise SystemExit("CHARACTER_ANALYSIS_INDEX.md is out of date")
        return 0
    if args.snapshot == "commit":
        raise DomainError("commit-snapshot generation is check-only")
    atomic_write_text(output, rendered)
    return 0


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except DomainError as exc:
        raise SystemExit(f"FAIL: {exc}") from exc
